export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const EDIT_USER_DATA_SUCCESS = "EDIT_USER_DATA_SUCCESS";
export const EDIT_USER_DATA_FAILURE = "EDIT_USER_DATA_FAILURE";
export const EDIT_USER_DATA_LOCAL = "EDIT_USER_DATA_LOCAL";
export const PRELOADER_CLOSE = "PRELOADER_CLOSE";

export const RECIPES_REQUEST = "RECIPES_REQUEST";
export const RECIPES_GET_SUCCESS = "RECIPES_GET_SUCCESS";
export const RECIPES_GET_FAILURE = "RECIPES_GET_FAILURE";
export const RECIPES_ADD_ITEM_SUCCESS = "RECIPES_ADD_ITEM_SUCCESS";
export const RECIPES_ADD_ITEM_FAILURE = "RECIPES_ADD_ITEM_FAILURE";
export const RECIPES_EDIT_ITEM_SUCCESS = "RECIPES_EDIT_ITEM_SUCCESS";
export const RECIPES_EDIT_ITEM_FAILURE = "RECIPES_EDIT_ITEM_FAILURE";
export const RECIPES_DELETE_ITEM_SUCCESS = "RECIPES_DELETE_ITEM_SUCCESS";
export const RECIPES_DELETE_ITEM_FAILURE = "RECIPES_DELETE_ITEM_FAILURE";
export const RECIPES_LOG_OUT = "RECIPES_LOG_OUT";

export const USER_FROM_JWT = "USER_FROM_JWT";
